### ISSUE TITLE
$validates_length_of não funciona

### ISSUE THREAD

**Issue by dflourusso** [paliari/doctrine-validator#1]
Se ele pegar o valor default do doctrine funciona, mas se eu sobrescrever a propriedade no model não. Ele dá erro direto do banco de dados, como se nem estivesse validando.

Exemplo de uso: 

``` php
protected static $validates_length_of     = [
    'codigo'    => ['maximum' => 25],
    'descricao' => ['maximum' => 255],
    'obs'       => ['maximum' => 65535]
];
```

**Comment by paliari** [comment]
O problema era o array_merge_recursive do php, já corrigido na versão 1.1.2.
